### ISSUE TITLE
Don't buffer complete files

### ISSUE THREAD

**Issue by HermanMolinder** [wisinorden/iptvutils#14]
Today the application reads and buffer the complete input file. If the file is very large it will eat all your memory. To solve this parts of the file could be buffered during playback/convert.

**Comment by Cheesier** [comment]
The input buffer can only grow to a specified size, 1024 packets if i recall. This was (somewhat) tested with 1+ GB files.

**Comment by HermanMolinder** [comment]
Sorry, I misunderstood Emil. You're right.
