### ISSUE TITLE
Wrong scaling after switch graph source and then back again

### ISSUE THREAD

**Issue by maxha651** [wisinorden/iptvutils#31]
Tested with 37.5 Mbit/s CBR. After running a few seconds and then stopping it looks like this with som nice padding on top and bottom of line:

![before](https://user-images.githubusercontent.com/6904747/61031900-b78c8a00-a3c0-11e9-97ae-86212673b8a4.png)

After switching to IAT and then back again it looks like this:
![after](https://user-images.githubusercontent.com/6904747/61032011-e86cbf00-a3c0-11e9-9d95-4e029a3e6f0c.png)

The IAT looks the same.

**Comment by marre914** [comment]
Scaling needs to be adapted to multiple streams. Each stream needs min and max bitrate & iat values or something similar
